/**
 * First aid and red-flag replies bundled with the app, so they work offline.
 * Generated by backend/scripts/export_offline_safety.py; do not edit the JSON.
 */
import data from '../data/offlineSafety.json';

const medical = new RegExp(data.medical.patterns.join('|'), 'i');
const selfHarm = new RegExp(data.self_harm.patterns.join('|'), 'i');

export const offlineProtocols: Record<string, any> = data.protocols;

/** The server's fixed reply for a red-flag message, or null. Self-harm is checked first, as on the server. */
export function offlineRedFlagReply(text: string): string | null {
  if (selfHarm.test(text)) return data.self_harm.reply;
  if (medical.test(text)) return data.medical.reply;
  return null;
}
