"""Raw DNA files are parsed into a fixed panel; nothing reports a personal disease probability."""
import io
import zipfile

from app.services.genomics_insights import GenomicsInsightsService, parse_raw_file

TWENTYTHREE = """# This data file generated by 23andMe
# rsid\tchromosome\tposition\tgenotype
rs7903146\t10\t114758349\tCT
rs9939609\t16\t53820527\tTT
rs429358\t19\t45411941\tTC
rs7412\t19\t45412079\tCC
rs4244285\t10\t96541616\tAA
rs1799853\t10\t96702047\tCT
rs1057910\t10\t96741053\tAA
rs4988235\t2\t136608646\tGG
rs1815739\t11\t66328095\t--
rs999999\t1\t1\tAA
"""

ANCESTRY = """#AncestryDNA raw data download
rsid\tchromosome\tposition\tallele1\tallele2
rs7903146\t10\t114758349\tT\tT
rs4149056\t12\t21331549\tT\tC
"""


def _svc(text: str) -> tuple[GenomicsInsightsService, dict]:
    svc = GenomicsInsightsService()
    return svc, svc.upload(text.encode())


def test_parses_both_layouts_and_zip():
    assert parse_raw_file(TWENTYTHREE.encode())["rs7903146"] == "CT"
    assert "rs1815739" not in parse_raw_file(TWENTYTHREE.encode())  # no-call
    assert "rs999999" not in parse_raw_file(TWENTYTHREE.encode())  # off panel
    assert parse_raw_file(ANCESTRY.encode()) == {"rs7903146": "TT", "rs4149056": "TC"}
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w") as zf:
        zf.writestr("genome.txt", TWENTYTHREE)
    assert parse_raw_file(buf.getvalue())["rs4244285"] == "AA"


def test_associations_carry_source_and_no_personal_risk():
    _, report = _svc(TWENTYTHREE)
    tcf = next(a for a in report["associations"] if a["gene"] == "TCF7L2")
    assert tcf["copies"] == 1 and tcf["source"] and tcf["odds_ratio_per_copy"] == 1.4
    flat = str(report).lower()
    for banned in ("risk_score", "probability", "health_score", "methylfolate"):
        assert banned not in flat


def test_apoe_hidden_until_asked():
    svc, report = _svc(TWENTYTHREE)
    assert report["apoe"] == {"available": True, "shown": False, "counselling": report["apoe"]["counselling"]}
    shown = svc.set_show_apoe(True)["apoe"]
    assert shown["genotype"] == "e3/e4" and shown["odds_ratio"] == 3.2


def test_pgx_phenotypes_follow_cpic():
    _, report = _svc(TWENTYTHREE)
    pgx = {p["gene"]: p for p in report["pharmacogenomics"]}
    assert pgx["CYP2C19"]["phenotype"] == "Poor metabolizer"
    assert pgx["CYP2C9"]["phenotype"] == "Intermediate metabolizer"  # *1/*2, activity 1.5
    assert pgx["SLCO1B1"]["status"] == "not_in_file"
    assert pgx["CYP2D6"]["status"] == "not_callable"
    assert "Do not change" in pgx["CYP2C19"]["action"]


def test_drug_check_names_prescriber_not_dose():
    svc, _ = _svc(TWENTYTHREE)
    out = svc.check_drugs(["Clopidogrel", "paracetamol"])
    assert [r["drug"] for r in out["results"]] == ["clopidogrel"]
    assert "prescriber" in out["results"][0]["message"]


def test_unreadable_file_keeps_nothing():
    svc, out = _svc("hello world")
    assert out["status"] == "unreadable" and svc.report()["status"] == "no_data"
