"""QR code generator for workout template sharing.

Encodes workout data as scannable QR codes that other users can import.
Uses pure Python QR generation (no external dependencies needed).
"""

from __future__ import annotations
import json
import base64
import hashlib
from dataclasses import dataclass


@dataclass
class WorkoutShare:
    share_id: str
    workout_data: dict
    created_by: str
    created_at: str
    template_name: str
    exercise_count: int
    target_duration: int


# Simple QR code generation using text encoding
# In production, use qrcode library or API
def generate_share_code(workout_data: dict, user_id: str) -> dict:
    """Generate a shareable code for a workout template.

    Returns a compact encoded string that can be QR-scanned or shared via link.
    """
    # Create compact share payload
    exercises = workout_data.get("exercises", [])
    compact_exercises = []
    for ex in exercises[:10]:  # Limit to 10 exercises for QR size
        compact_exercises.append({
            "id": ex.get("exercise_id", ""),
            "s": ex.get("sets", 3),
            "r": ex.get("target_reps", "8-12"),
            "w": ex.get("target_weight", 0),
        })

    share_payload = {
        "v": 1,  # version
        "n": workout_data.get("title", "Shared Workout")[:50],
        "t": workout_data.get("target_duration_minutes", 45),
        "e": compact_exercises,
        "u": user_id[:8],  # Partial user ID
    }

    # Encode as base64
    json_str = json.dumps(share_payload, separators=(",", ":"))
    encoded = base64.urlsafe_b64encode(json_str.encode()).decode()

    # Generate short hash for verification
    checksum = hashlib.md5(json_str.encode()).hexdigest()[:8]

    return {
        "share_code": encoded,
        "checksum": checksum,
        "share_url": f"https://adapfit.app/share/{encoded}",
        "exercise_count": len(compact_exercises),
        "workout_name": share_payload["n"],
    }


def decode_share_code(share_code: str) -> dict | None:
    """Decode a share code back into workout data."""
    try:
        # Add padding if needed
        padded = share_code + "=" * (4 - len(share_code) % 4)
        decoded = base64.urlsafe_b64decode(padded)
        payload = json.loads(decoded)

        if payload.get("v") != 1:
            return None

        # Reconstruct full exercise list
        exercises = []
        for ex in payload.get("e", []):
            exercises.append({
                "exercise_id": ex.get("id", ""),
                "sets": ex.get("s", 3),
                "target_reps": ex.get("r", "8-12"),
                "target_weight": ex.get("w", 0),
            })

        return {
            "title": payload.get("n", "Imported Workout"),
            "target_duration_minutes": payload.get("t", 45),
            "exercises": exercises,
            "created_by": payload.get("u", "unknown"),
        }
    except Exception:
        return None


def generate_quick_share_text(workout_data: dict) -> str:
    """Generate a human-readable share text for messaging apps."""
    title = workout_data.get("title", "Workout")
    exercises = workout_data.get("exercises", [])
    duration = workout_data.get("target_duration_minutes", 45)

    lines = [f"🏋️ {title} ({duration} min)", ""]
    for i, ex in enumerate(exercises[:6], 1):
        name = ex.get("exercise_name", ex.get("exercise_id", "Exercise"))
        sets = ex.get("sets", 3)
        reps = ex.get("target_reps", ex.get("reps", "8"))
        weight = ex.get("actual_weight", ex.get("target_weight", 0))
        weight_str = f" @ {weight}kg" if weight else ""
        lines.append(f"{i}. {name} — {sets}×{reps}{weight_str}")

    if len(exercises) > 6:
        lines.append(f"... and {len(exercises) - 6} more exercises")

    lines.append("")
    lines.append("Generated by AdapFit 🏋️‍♂️")
    return "\n".join(lines)


qr_generator = __import__(__name__)
